apiVersion: v1
kind: ConfigMap
metadata:
  name: order-support-config
data:
  POSTGRES_DB: order_support
  POSTGRES_USER: order_support
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_support
  REDIS_HOST: redis
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_USERNAME: order_support
  ORDER_SERVICE_URL: http://order-service:8081
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE: readinessState,db
